version: 2
jobs:
  build:

    working_directory: ~/repo

    docker:
      - image: circleci/node:10.20.1

    steps:
      - checkout

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}

      - run: npm run test

