version: 2.1
jobs:
  build:

    working_directory: ~/project

    docker:
      - image: circleci/node:10.20.1

    steps:

      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}

      - run:
          name: Install
          command: npm i

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}

      - run:
          name: Tets
          command: npm run test

      - run:
          name: Lint Json
          command: npm run lint:json

