version: 2.1
jobs:
  build:
    working_directory: ~/project

    docker:
      - image: cimg/node:16.14.2

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}

      - run:
          name: Install
          command: npm i

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "package.json" }}

      - run:
          name: Format check
          command: npm run format:check

      - run:
          name: Test
          command: npm run test
